// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DateStripController from "./date_strip_controller"
application.register("date-strip", DateStripController)

import DietSwapController from "./diet_swap_controller"
application.register("diet-swap", DietSwapController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import IngredientRowsController from "./ingredient_rows_controller"
application.register("ingredient-rows", IngredientRowsController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import ToggleMealController from "./toggle_meal_controller"
application.register("toggle-meal", ToggleMealController)
