// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DietSwapController from "./diet_swap_controller"
application.register("diet-swap", DietSwapController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ToggleMealController from "./toggle_meal_controller"
application.register("toggle-meal", ToggleMealController)
