// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DietSwapController from "./diet_swap_controller"
application.register("diet-swap", DietSwapController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ToggleMealController from "./toggle_meal_controller"
application.register("toggle-meal", ToggleMealController)
