# x-base: &base
#   build:
#     context: .
#     dockerfile: ./Dockerfile.dev
#     args:
#       RUBY_VERSION: '3.3.5'
#   stdin_open: true
#   tty: true
#   volumes:
#     - .:/app:cached
#   depends_on:
#     - redis
#     - postgres

volumes:
  redis:
  # postgres:

services:
  redis:
    image: redis:6
    restart: unless-stopped
    ports:
      - '63790:6379'
    volumes:
      - redis:/data

  # postgres:
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - 54320:5432

  # app:
  #   <<: *base
  #   command: bash -c "bin/rails server -p 3000 -b 0.0.0.0"
  #   ports:
  #     - '3000:3000'

  # css:
  #   <<: *base
  #   command: bash -c "yarn build:css --watch"

  # js:
  #   <<: *base
  #   command: bash -c "yarn build --watch"

  # sidekiq:
  #   <<: *base
  #   command: bundle exec sidekiq -C config/sidekiq.yml
