development:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url %>
  channel_prefix: dieting_app_production
