default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url:  <%= ENV.fetch("DATABASE_URL") { 'localhost' } %>

development:
  <<: *default
  database: diet_app_development
  url: <%= Rails.application.credentials.database_url %>

test:
  <<: *default
  database: diet_app_test

production:
  <<: *default
  database: diet_app_production
  url: <%= Rails.application.credentials.database_url %>
