default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url:  <%= ENV.fetch("DATABASE_URL") { 'localhost' } %>

development:
  <<: *default
  database: diet_app_development
  url: <%= ENV.fetch("DATABASE_URL") { Rails.application.credentials.fetch(:database_url, 'postgres://localhost/diet_app_development') } %>

test:
  <<: *default
  database: diet_app_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { Rails.application.credentials.fetch(:database_url, 'postgres://localhost/diet_app_production') } %>
