default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # 5432 for local, 54320 for Docker Compose
  url: <%= ENV.fetch("DATABASE_URL") { Rails.application.credentials.fetch(:database_url, 'postgres://localhost/diet_app_development') } %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { Rails.application.credentials.fetch(:database_url, 'postgres://localhost/diet_app_test') } %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { Rails.application.credentials.fetch(:database_url, 'postgres://localhost/diet_app_production') } %>
