default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: diet_app_development
  url: <%= Rails.application.credentials.database_url %>

test:
  <<: *default
  host: postgres
  username: postgres
  password: postgres
  database: diet_app_test

production:
  <<: *default
  database: diet_app_production
  url: <%= Rails.application.credentials.database_url %>
